### ISSUE TITLE
crash because of an out of memory error

### ISSUE THREAD

**Issue by Yarith** [stil4m/elm-analyse#160]
Hi,

i got a crash caused by an out of memory error today. It seems to be related to a type alias for a record which got not used for the generic parameter of List. 

I have created a short as possible example where it happens on my computer everytime i run "elm-analyse" in the command line. You can find it at the end of this post. I used the version 0.14.2 on windows 10. elm-format-0.18 0.6.1-alpha is currently installed.

There are several ways to get rid of the out of memory error, these are:
- using the AnimatablePath type alias for the staticGeometryList function. 
```elm
staticGeometryList : List { geometry : Int, attributes : List (Html Msg) }
``` 
becomes 
```elm 
staticGeometryList : List AnimatablePath
```
- removing one of the createSvg, init, update, subscriptions or view functions. The Msg type alias can not be removed, because i need to export something.
- moving at least one of createSvg, init, update, subscription and view functions above the staticGeometryList function. Are all 5 below staticGeometryList it gives the out of memory error.
- changing the return type of the staticGeometryList function to a non generic one
- removing the function declaration of the staticGeometryList and let it throw a missing declaration warning instead

Which does not help:
- moving the AnimatablePath type alias below the staticGeometryList function
- moving type aliases in general does not affect anything
- changing the declaration of staticGeometryList from List to Maybe
- removing the elm-stuff folder and reinstall all packages with elm-package install.

I came to the problem, because i had left out the declaration of the staticGeometryList function and used the code fix of vscode to let it generate it for me. After i saved the document i noticed that the elm-analyse server has crashed.

elm-package.json
```json
{
    "version": "1.0.0",
    "license": "MIT",
    "repository": "https://github.com/user/project.git",
    "summary": "Test project where elm-analyse 0.14.2 crashes with oom",
    "source-directories": [
        "."
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-lang/core": "5.1.1 <= v < 6.0.0",
        "elm-lang/html": "2.0.0 <= v < 3.0.0"
    },
    "elm-version": "0.18.0 <= v < 0.19.0"
}
```

Index.elm
```elm
module Index exposing (Msg)

import Html exposing (Html, div)


type alias AnimatablePath =
    { geometry : Int, attributes : List (Html Msg) }


staticGeometryList : List { geometry : Int, attributes : List (Html Msg) }
staticGeometryList =
    []


createSvg : AnimatablePath -> Html Msg
createSvg _ =
    div [] []


type alias Msg =
    ()


init : ( Int, Cmd Msg )
init =
    ( (), Cmd.none )


update : Msg -> Int -> ( Int, Cmd Msg )
update _ model =
    ( model, Cmd.none )


view : Int -> Html Msg
view _ =
    div [] []


subscriptions : Int -> Sub Msg
subscriptions _ =
    Sub.none
```

The output of elm-package after deleting elm-stuff is:
```
> elm-package install
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 5.1.1
    elm-lang/html 2.0.0
    elm-lang/virtual-dom 2.0.4

Do you approve of this plan? [Y/n] Y
Starting downloads...

  ÔùÅ elm-lang/html 2.0.0
  ÔùÅ elm-lang/virtual-dom 2.0.4

ÔùÅ elm-lang/core 5.1.1
Packages configured successfully!
```

Output to the command line
```
> elm-analyse
Cached package information invalidated. Fetching new data from package.elm-lang.org
Fetched dependencies
SyntaxError: Unexpected token T in JSON at position 1
    at JSON.parse (<anonymous>)
    at setupCache (%appdata%\npm\node_modules\elm-analyse\js\util\format-service.js:45:43)
    at module.exports (%appdata%\npm\node_modules\elm-analyse\js\util\format-service.js:58:5)
    at module.exports (%appdata%\npm\node_modules\elm-analyse\js\fileReader.js:8:59)
    at module.exports (%appdata%\npm\node_modules\elm-analyse\js\util\file-loading-ports.js:8:48)
    at %appdata%\npm\node_modules\elm-analyse\js\analyser.js:22:9
    at %appdata%\npm\node_modules\elm-analyse\js\util\dependencies.js:34:9
    at Request._callback (%appdata%\npm\node_modules\elm-analyse\js\util\dependencies.js:19:9)
    at Request.self.callback (%appdata%\npm\node_modules\elm-analyse\node_modules\request\request.js:186:22)
    at emitTwo (events.js:125:13)
INFO: No configuration provided. Using default configuration.
INFO: Load dependency elm-lang/core 5.1.1
INFO: Load dependency elm-lang/html 2.0.0
INFO: Load file Index.elm...


#
# Fatal error in , line 0
# API fatal error handler returned after process out of memory
#

==== C stack trace ===============================

        v8_inspector::protocol::Runtime::API::StackTrace::fromJSONString [0x00007FF6DF95D8E1+47217]
        v8::internal::Malloced::operator delete [0x00007FF6DF25D201+18497]
        v8_inspector::protocol::Runtime::API::StackTrace::fromJSONString [0x00007FF6DF95FD27+56503]
        v8::internal::FatalProcessOutOfMemory [0x00007FF6DF518CC2+162]
        v8::internal::IdentityMapBase::NextIndex [0x00007FF6DF5743B3+24131]
        v8::internal::IdentityMapBase::NextIndex [0x00007FF6DF5741CC+23644]
        v8::internal::IdentityMapBase::NextIndex [0x00007FF6DF5850F0+93056]
        v8::internal::IdentityMapBase::NextIndex [0x00007FF6DF57EA10+66720]
        v8::internal::IdentityMapBase::NextIndex [0x00007FF6DF57E597+65575]
        v8::internal::IdentityMapBase::NextIndex [0x00007FF6DF5888EA+107386]
        v8::internal::Malloced::operator delete [0x00007FF6DF263A8F+45263]
        v8_inspector::protocol::Runtime::API::StackTrace::fromJSONString [0x00007FF6DF95F68E+54814]
        uncompress [0x00007FF6DFDC90A5+134293]
        BaseThreadInitThunk [0x00007FFFB4CC1FE4+20]
        RtlUserThreadStart [0x00007FFFB4EAF061+33]
```

**Comment by stil4m** [comment]
1. What version of elm-format are you using? The `SyntaxError: Unexpected token T in JSON at position 1` worries me.
1. Could you remove the `elm-stuff` directory and, try again? Does this resolve the issue?

**Comment by Yarith** [comment]
Currently elm-format-0.18 0.6.1-alpha is installed. I tried to update it with ```npm install-elm format -g``` but it resulted in the same version. I installed the elm-format-0.18 0.7.0-exp version. The T-SyntaxError is gone after i delete the elm-stuff folder - with both versions of elm-format. On second run it appears again.

This is the output with elm-format-0.18 0.7.0-exp after i removed the elm-stuff folder:
```
> elm-analyse --version
0.14.2
> elm-format --help
elm-format-0.18 0.7.0-exp
...
> elm-package install
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 5.1.1
    elm-lang/html 2.0.0
    elm-lang/virtual-dom 2.0.4

Do you approve of this plan? [Y/n] Y
Starting downloads...

  ÔùÅ elm-lang/html 2.0.0
  ÔùÅ elm-lang/virtual-dom 2.0.4

ÔùÅ elm-lang/core 5.1.1
Packages configured successfully!
> elm-analyse
INFO: No configuration provided. Using default configuration.
INFO: Load dependency elm-lang/core 5.1.1
INFO: Load dependency elm-lang/html 2.0.0
INFO: Load file Index.elm...

<--- Last few GCs --->

[9928:0000026FE1579700]     8264 ms: Mark-sweep 1399.9 (1442.8) -> 1399.9 (1447.3) MB, 785.5 / 0.0 ms  allocation failure scavenge might not succeed
[9928:0000026FE1579700]     9063 ms: Mark-sweep 1404.0 (1447.3) -> 1404.0 (1458.8) MB, 797.5 / 0.0 ms  allocation failure scavenge might not succeed
[9928:0000026FE1579700]    10024 ms: Mark-sweep 1415.7 (1458.8) -> 1415.8 (1458.8) MB, 956.0 / 0.0 ms  allocation failure scavenge might not succeed


<--- JS stacktrace --->
Cannot get stack trace in GC.
FATAL ERROR: MarkCompactCollector: semi-space copy, fallback in old gen Allocation failed - JavaScript heap out of memory
```

On the second run without deleting elm-stuff the T-SyntaxError appeared again:
```
> elm-analyse
SyntaxError: Unexpected token T in JSON at position 1
    at JSON.parse (<anonymous>)
    at setupCache (%appdata%\npm\node_modules\elm-analyse\js\util\format-service.js:45:43)
    at module.exports (%appdata%\npm\node_modules\elm-analyse\js\util\format-service.js:58:5)
    at module.exports (%appdata%\npm\node_modules\elm-analyse\js\fileReader.js:8:59)
    at module.exports (%appdata%\npm\node_modules\elm-analyse\js\util\file-loading-ports.js:8:48)
    at %appdata%\npm\node_modules\elm-analyse\js\analyser.js:22:9
    at %appdata%\npm\node_modules\elm-analyse\js\util\dependencies.js:57:17
    at %appdata%\npm\node_modules\elm-analyse\js\util\cache.js:33:13
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:504:3)
INFO: No configuration provided. Using default configuration.
INFO: Load dependency elm-lang/core 5.1.1
INFO: Load dependency elm-lang/html 2.0.0
INFO: Load file Index.elm...


#
# Fatal error in , line 0
# API fatal error handler returned after process out of memory
#


#
# Fatal error in , line 0
# API fatal error handler returned after process out of memory
#

==== C stack trace ===============================


==== C stack trace ===============================

        v8_inspector::protocol::Runtime::API::StackTrace::fromJSONString [0x00007FF798A7D8E1+   v8_inspector::protocol::Runtime::API::StackTrace::fromJSONString [0x00007FF798A7D8E1+47217]
47217]
                v8::internal::Malloced::operator delete [0x00007FF79837D201+18497]
v8::internal::Malloced::operator delete [0x00007FF79837D201+18497]
        v8_inspector::protocol::Runtime::API::StackTrace::fromJSONString [0x00007FF798A7FD27+56503]
        v8_inspector::protocol::Runtime::API::StackTrace::fromJSONString [0x00007FF798A7FD27+56503]
        v8::internal::FatalProcessOutOfMemory [0x00007FF798638CC2+162]
        v8::internal::FatalProcessOutOfMemory [0x00007FF798638CC2+162]
        v8::internal::IdentityMapBase::NextIndex [0x00007FF7986943B3+24131]
        v8::internal:
```

The out of memory error is still there. It looks a little bit different everytime, but every output says something about out of memory.

**Comment by stil4m** [comment]
I've created an version of elm-analyse (`0.15.0-alpha.2`) in which this is supposed to be fixed. You can install it using:

```
npm install elm-analyse@0.15.0-alpha.2
```

Can you verify if this is resolved? Thanks

**Comment by DawidJanczak** [comment]
Not the author of this issue, but it fixed it for me. Thanks!

**Comment by bardt** [comment]
Can also confirm it working. But I also can't start the server in this version:

```
$ elm-analyse -s
Elm Analyser server starting with config:
{ port: 3000,
  elmFormatPath: 'elm-format',
  format: 'human',
  open: false }
module.js:549
    throw err;
    ^

Error: Cannot find module 'open'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/bardt/.nvm/versions/node/v8.11.1/lib/node_modules/elm-analyse/js/server/worker.js:1:76)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by stil4m** [comment]
@bardt Thanks for testing it. Just fixed the missing module in [this commit](https://github.com/stil4m/elm-analyse/commit/e7b55259cef0d2f664486a81841febda460b4db3) (new alpha available though). Issue was introduced in #162 due to a dependency listed under devDependencies.

**Comment by brianvanburken** [comment]
I can also attest that it fixes the problem I reported above 👍

**Comment by Yarith** [comment]
I can also confirm that it is fixed with version 0.15.0-alpha.3. Tested it on my simple example and the real project where i encountered it first.

**Comment by stil4m** [comment]
Thanks everyone for testing this out. I'll be releasing this soon in a GA release.

**Comment by Birowsky** [comment]
ping..

**Comment by stil4m** [comment]
I'm working a few things out before the 0.15 release. It will be released as soon as I figure that out.

@Birowsky This does not work. Constructive messages are much more valuable. Like "at this point I cant use elm-analyse at all, I need this new version to resolve it". For example, I can response with "at this point you can use the 0.15.0-alpha safely, what is in there will be released in the stable version *soon*", or "maybe you can downgrade to a version prior to `0.14.2`, because from the reports this version seems to introduce the bug". I really do not want to sound harsh, I just dont think that messages such as "like", "ping", "this must be fixed or the world exploded" help in the proces of bringing this tool forward.

**Comment by Birowsky** [comment]
Dammit. Sorry. Never meant to be hurtful. This is what I thought when I wrote 'ping': This seems like such a cool tool! I can barely wait to use it.

Sorry again. I have the outmost respect for folks enriching the Elm ecosystem!
