### ISSUE TITLE
Elm 0.19

### ISSUE THREAD

**Issue by romariolopezc** [stil4m/elm-analyse#176]
```sh
$ elm-analyse -s -o
There is no elm-package.json file in this directory. elm-analyse will only work in directories where such a file is located.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Elm 0.19 uses `elm.json`

**Comment by stil4m** [comment]
`elm-analyse` is not yet compatible with Elm 0.19. This is work in progress. Once elm-analyse is upgraded to 0.19, 0.18 will not be supported anymore. `elm-analyse@0.15` is the latest version that will support Elm 0.18.

**Comment by andys8** [comment]
@stil4m Will this be a single, large pull request or are multiple issues to be tackled? Is the scope of the necessary changes a ailable somewhere?

**Comment by stil4m** [comment]
I've kind of finished working on the Elm `0.19` version. If you are able, and would like to test it, I would appreciate it very much.

* The branch is `0.19-upgrade`;
* You can build the project with node v6 (use nvm).
* `make && npm link` will build the whole thing and link it to your current node path.

If you run into issues building it / running it on your own project, please let me know via this thread. Thank you in advance.

**Comment by andys8** [comment]
I tried it and it looks good. As far as I can tell it's working as usual. I fixed 75 messages, most of them automatically.

I found one issue, but I'm not sure if it is new: The UI doesn't allow to click on updated version. I had a similar issue, with 0.19. I'll look into the source and verify if it's the issue I had or something else.

![image](https://user-images.githubusercontent.com/13085980/49044155-413e6d00-f1cd-11e8-838f-404d49d83e95.png)

**Comment by alex-tan** [comment]
Versions:

```
 elm-analyse (0.19-upgrade*) [04:18:06] $ node -v
v11.2.0
 elm-analyse (0.19-upgrade*) [04:18:17] $ npm -v
6.4.1
```

Getting many warnings when trying to `npm install` as well as these errors:

```
../../../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../fsevents.cc:6:
In file included from ../../../../nan/nan.h:192:
../../../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
```

`make && npm link` fails as well afterwards. Is there a particular node version you'd recommend running this on?

**Comment by alex-tan** [comment]
🤦‍♂️ thanks. My fault for skimming

**Comment by ronanyeah** [comment]
Going ok for me :+1: 
```
OS: Antergos Linux x86_64
Kernel: 4.19.4-arch1-1-ARCH
```

Steps:
- `git checkout 0.19-upgrade`
- `npm i`
- `nvm i 6`
- `make && npm link`

**Comment by klaftertief** [comment]
Just found a tiny issues. Refreshing the browser on `/tree` returns the raw JSON, and not the Elm app. At least in Safari and Chrome on macOS.

**Comment by tlentz** [comment]
ETA on when we can use this for 0.19?

**Comment by stil4m** [comment]
Currently on master. Will run some few last tests. And then release it to NPM.
